name: mostar-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - fastp
  - filtlong
  - flye
  - blast>=2.9
  - medaka>=2.2.0
  - bwa
  - polypolish
  - prokka
  - perl-xml-simple   
  - perl-time-hires    
  - perl-digest-md5    
  - ncbi-amrfinderplus
  - samtools
  - minimap2
  - pip
