name: mostar-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - fastp
  - filtlong
  - flye
  - blast>=2.9
  - medaka>=2.2.0
  - bwa
  - polypolish
  - prokka>=1.14.6
  - perl-xml-simple   
  - perl-time-hires    
  - perl-digest-md5
  - perl-bio-searchio-hmmer
  - perl-bioperl
  - ncbi-amrfinderplus
  - samtools
  - minimap2
  - pip
