name: mostar_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  # Core Assembly & Polishing 
  - flye
  - medaka
  - filtlong
  - polypolish
  # Pre-processing & Alignment
  - fastp
  - bwa
  - samtools
  - bcftools
  - minimap2
  - circlator
  # Annotation & Profiling
  - bakta
  - ncbi-amrfinderplus
  - blast
  - kraken2
  # ICE & Conjugation Detection
  - macsyfinder
  # Plasticity & Mobile Elements
  - genomad
  # Python Libraries for Visualization & Reports
  - matplotlib
  - numpy
  - pandas
  - biopython
  # Supporting Utilities
  - setuptools<70
  - micromamba
  - osfclient
  - wget
  - curl
